### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by g0ttferd0m** [soifou/docker-lamp#2]
Hello,
I've followed the readme to install like it's written step by step, but in my browser I've "File not found".
I've created a folder in my home called "Development" to not change the conf file of docker compose, created new entry in hosts file for local.dev, but php-fpm seems to look in wrong folder.

**Comment by soifou** [comment]
Hi @g0ttferd0m 

Thanks for trying it, did you create a conf file in `nginx/conf.d/000-default.conf` with this content :

```
server {
    listen       80;
    server_name  local.dev;
    root   /app;
    include snippets/basic-php.conf;
}
```

If so it will look for an index.php file located in `/home/xxx/Development/index.php`

Don't forget to restart the web container if you modify the nginx configuration files.

**Comment by g0ttferd0m** [comment]
Hi,
Thank you for your quick response.
Yes I've copied `000-default.conf.dist` to `000-default.conf` and I've created directory `Development` in my home folder (where I put a basic index.php with phpinfo()).
Here is my conf file : 
```cat nginx/conf.d/000-default.conf
 server {
    listen       80;  
    server_name  local.dev;  
    root   /app;  
    include snippets/basic-php.conf;  
}
```

Restarting containers : 
```dockercomp restart php web
Restarting lamp_web ... done
Restarting lamp_php ... done
```

My hosts file : 
```cat /etc/hosts
# IP-Address  Full-Qualified-Hostname  Short-Hostname
# 
127.0.0.1       localhost
127.0.0.1       local.dev
```

And my browser at local.dev : 

![image](https://user-images.githubusercontent.com/11997724/35846404-d4dbcf42-0b16-11e8-8a65-511fa6d760d1.png)

Maybe I've missed something else? Thanks for your help.

Edit :  When I use shell of PHP docker, I see nothing in /app, and it's impossible to create dir. Maybe that's help to find what's wrong.

**Comment by soifou** [comment]
That's a hint! You should have the content of your `~/Development` mapped in your docker `/app` folder for web and php containers.

In your `docker-compose.yml` check the web and php container map the same volume:
```
web:
    [...]
    volumes:
        - ~/Development:/app
php:
    [...]
    volumes:
        - ~/Development:/app
```

Then kill and restart your containers : 
```
$ docker-compose stop web php && docker-compose rm -f
$ docker-compose up -d
```

Finally check it lists your index.php from /app :
```
$ docker-compose exec web ls /app
$ docker-compose exec php ls /app
```

**Comment by g0ttferd0m** [comment]
Ok, 
here is my docker-compose.yml : 
```
web:
        image: nginx:1.13-alpine
        container_name: lamp_web
        ports:
            - 80:80
        volumes:
            - ~/Development:/app
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/snippets:/etc/nginx/snippets
            - ./nginx/rewrites:/etc/nginx/rewrites

    php:
        image: soifou/php-alpine:fpm-7.2
        container_name: lamp_php
        volumes:
            - ~/Development:/app
            - ./php/php.ini:/usr/local/etc/php/conf.d/50-settings.ini
        ports:
            - 9000:9000
```
(I've cloned your repo and haven't modified anything).
Stoping and removing : 
```
dockercomp stop web php && dockercomp rm -f
Stopping lamp_web ... done
Stopping lamp_php ... done
Going to remove lamp_web, lamp_php
Removing lamp_web ... done
Removing lamp_php ... done
```
After docker-compose up -d, I did the ls and I've still nothing : 
```
 ~/Documents/Dev/docker-lamp > dockercomp exec web ls /app
~/Documents/Dev/docker-lamp > dockercomp exec php ls /app
~/Documents/Dev/docker-lamp >
```
So I suppose it's about rights problem, I keep looking in this way.

Edit : I've tried to change ~/Development folder to another and I still have the problem, Docker seems to don't map folder to /app. I don't know why.

**Comment by soifou** [comment]
Hmm this is not about permission problem, maybe a dumb question but did you create a `~/Development` folder on your host machine and an index.php file in there ?

I see you clone this repo in `~/Documents/Dev` so maybe you want to server all you dev content from there instead...

**Comment by g0ttferd0m** [comment]
Yes I've created the right folder : 
![image](https://user-images.githubusercontent.com/11997724/35852269-bbd3408e-0b2a-11e8-9ae8-093276d75faf.png)
And yes the clone is in ~/Documents/Dev

**Comment by g0ttferd0m** [comment]
I've resolved the issue by creating and map dir inside the clone folder.
![image](https://user-images.githubusercontent.com/11997724/35853396-aaa04e12-0b2d-11e8-9a4e-c570ba85e20f.png)

So here is my new conf file.
```
services:
    web:
        image: nginx:1.13-alpine
        container_name: lamp_web
        ports:
            - 80:80
        volumes:
            - ./www:/app
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/snippets:/etc/nginx/snippets
            - ./nginx/rewrites:/etc/nginx/rewrites

    php:
        image: soifou/php-alpine:fpm-7.2
        container_name: lamp_php
        volumes:
            - ./www:/app
            - ./php/php.ini:/usr/local/etc/php/conf.d/50-settings.ini
        ports:
            - 9000:9000
```
And the ls result after stoping/removing/restarting php & web dockers : 
```
dockercomp exec web ls /app
index.php 
```
And in the nav : 
![image](https://user-images.githubusercontent.com/11997724/35853528-05c42034-0b2e-11e8-9db5-ac88a2bd639d.png)

Thanks for you help! Was a great way to improve my docker skills.
